language: android
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-24.0.0
  - android-23
  - extra-google-m2repository
  - extra-android-m2repository
script: "./gradlew test assD"
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
notifications:
  webhooks:
  - http://pulse.pivotallabs.com/projects/3bc31568-d776-4012-ae6b-70cfa8958e87/status
deploy:
  provider: s3
  access_key_id: AKIAI7JZP65PKIFU7RFQ
  secret_access_key:
    secure: Y58qQ5WntVtGWgPrP4q3vzcNKr4C6LNXPhVF92xadu5t2Bf13ZH5mhyb5qrjLasxNMAmvsUtseMb4I4YW+eUsVDiIpxkh3YKLYsJjpi0w4Q7CJSjHUXSxEZW/7vH8NItugoouOtbb8hXJdd0aGlUe+YBxkViWORbbFTBp/FQZyH14h0hEbV1zCdMm8pcicZFz5CFI2huqO1qa7m8YHrgePWNXRXi0sd01mUPlooenjCkk6Uit6x5DqHTC3uq5uxbqgf9bSH/fhpyWp5YzrMWflvypMRxM+CqlZkSVKMuONAIVznZcTxjO53AJ6ue4/gZQFYIDUFoOOvCg7apnRcrnDoK2PviXVZ6w5F+8JS8bo+zVCXjCGqV3BWZqLdn2s1DTlEB57KrpGWNrUZ8ossVIYwygFyf/oIYsFWIALlbdHUmW0MCD4U0IXyowxYta//ewhMFcRKv5qYUNKdPT7/HnNicsC54t/m5FM1plUaYivjxtgXYAg0vF7bP/BvwHcGzdCfsXhEEqbGlp3Hv5HctswIzMu0pU+djQjVCqIodX0yP2wfKOJbVNsssW03vYY/cgeMhKF76XUrQgZfNj3OuAllBOCI+JaS4/HoiXKJstOwxcXcLFWbPkIheea4nmaivwg4jRT3zQtgNio0wnLp+h2PnoPZbA21gglOTZtsT9bc=
  bucket: todo-android
  skip_cleanup: true
  local-dir: app/build/outputs/apk/app-debug
  acl: public_read
  on:
    repo: pivotal-sydney/todo-android

